name: Generate Test Cases Based on Git Diff

on:
  push:
    branches:
      - main

jobs:
  generate-test-cases:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose Python version

      - name: Install requirements
        run: |
          echo "openai==0.27.0" > requirements.txt
          pip install -r requirements.txt

      - name: Get git diff
        id: git_diff
        run: |
          git diff HEAD~1 HEAD > diff.txt
          echo "Git diff output saved to diff.txt"
        
      - name: Call OpenAI API to generate test cases
        id: generate_test_cases
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Add your OpenAI API key in GitHub Secrets
        run: |
          DIFF_CONTENT=$(cat diff.txt)
          OPENAI_PROMPT="Generate test cases based on the following code changes:\n$DIFF_CONTENT"
          
          # Call the OpenAI API with the git diff as a prompt
          RESPONSE=$(curl https://api.openai.com/v1/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "text-davinci-003",  # Adjust model if needed
              "prompt": "'"${OPENAI_PROMPT}"'",
              "max_tokens": 500
            }' | jq -r '.choices[0].text')

          # Save response to a file
          echo "$RESPONSE" > response.txt

      - name: Display OpenAI response
        run: |
          cat response.txt
          echo "OpenAI test cases saved to response.txt"
      
      - name: Upload response file
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: response-file
          path: response.txt
