name: Generate Test Cases

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  generate_test_cases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract function definitions
        id: extract_info
        run: |
          echo "Extracting function definitions from main.py..."
          functions=$(grep -E 'def ' main.py | sed 's/^\s*//;s/\s*\(.*\):/\1/' | tr '\n' '; ')
          echo "::set-output name=data::$functions"

      - name: Send request to OpenAI API
        id: call_openai
        run: |
          echo "Sending request to OpenAI API..."
          response=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [{"role": "user", "content": "Generate test cases for the following functions: '"${{ steps.extract_info.outputs.data }}"'."}],
              "max_tokens": 500
            }')
          
          # Extract the AI response
          echo "$response" | jq -r '.choices[0].message.content' > response.txt

      - name: Save AI response to response.txt
        run: |
          echo "AI response saved to response.txt"
          cat response.txt

      - name: Commit and push response.txt
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add response.txt
          git commit -m "Add AI-generated test cases"
          git push origin main  # Change this to your default branch if needed
