name: Send Prompt to OpenAI

on:
  push:
    branches:
      - main  # Change this to your target branch if needed

jobs:
  send_prompt:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get last commit message and git diff
        id: get_commit_and_diff
        run: |
          # Get the last commit message
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          
          # Check if there's more than one commit
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            # Get the git diff between the last and previous commit
            GIT_DIFF=$(git diff HEAD^ HEAD)
          else
            # If there's only one commit, get the diff of the first commit
            GIT_DIFF=$(git show HEAD)
          fi

          # Set both as outputs to use them in the next step
          echo "::set-output name=message::$LAST_COMMIT_MESSAGE"
          echo "::set-output name=diff::$GIT_DIFF"

      - name: Send prompt to OpenAI and save response
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Get the last commit message and git diff from the previous step
          LAST_COMMIT_MESSAGE="${{ steps.get_commit_and_diff.outputs.message }}"
          GIT_DIFF="${{ steps.get_commit_and_diff.outputs.diff }}"

          # Prepare the prompt including the commit message and the git diff
          PROMPT="Based on the following commit message: \n\n'${LAST_COMMIT_MESSAGE}'\n\nAnd the changes made (git diff): \n\n${GIT_DIFF}\n\nPlease generate the necessary test cases."

          # Send request to OpenAI and capture the response
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -d '{
            "model": "gpt-3.5-turbo",
            "messages": [{"role": "system", "content": "You are a computer programmer assigned to generate test cases based on the git commit and diff."}, {"role": "user", "content": "'"$PROMPT"'"}]
          }' | jq -r '.choices[0].message.content')

          # Create a new file and write the response to it
          echo "$RESPONSE" > response.txt

      - name: Commit response file
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add response.txt
          git commit -m "Add OpenAI response based on last commit and diff"
          git push
